### PR TITLE
fixing exporters

### PR DESCRIPTION
**Pull request by xaerowalk**
Port mapping is incompatible with network_mode: host
reference: docker/compose#4799 (comment)

Also cAdvisor must be privileged too (tested in Ubuntu 16, 18)

### CODE REVIEW

**Comment by nightah** [comment]
The `docker-compose.exporters.yml` file is intended to capture the host's interfaces, hence the network_mode: host, though you are correct about the ports not being required in this instance.

I'll fix this up soon and remove the port mappings in the extended compose file.

Having said that not sure why you believe cAdvisor must be privileged, can you explain further what actual issue you're experiencing or trying to address here?

**Comment by xaerowalk** [comment]
> Having said that not sure why you believe cAdvisor must be privileged, can you explain further what actual issue you're experiencing or trying to address here?
>
This one: https://github.com/google/cadvisor/issues/2150
Processes section is blank at cadvisor:8080
`cadvisor        | W0415 09:47:17.312787       1 manager.go:353] Could not configure a source for OOM detection, disabling OOM events: open /dev/kmsg: no such file or directory
`
Tested in Ubuntu 16/18 and Centos 7 docker host.

**Comment by nightah** [comment]
I receive that same error message on bootup of the cAdvisor container:
`W0415 12:44:28.880127       1 manager.go:353] Could not configure a source for OOM detection, disabling OOM events: open /dev/kmsg: no such file or directory`

However I still see all my metrics, and do not have any issues with the provided dashboards, are you actually seeing an issue with the dashboards or just going based off that error?

**Comment by xaerowalk** [comment]
I had an issue with my own dashboard which based on process monitoring inside the container.

**Comment by nightah** [comment]
Could you please either share the dashboard or some of the queries you are trying to run that do not work?

To address the error about OOM events have you tried adding the following into your `docker-compose.yml`
```yml
  cadvisor:
    image: google/cadvisor:v0.33.0
    container_name: cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      # - /cgroup:/cgroup:ro #doesn't work on MacOS only for Linux
    devices:
      - /dev/kmsg:/dev/kmsg
    restart: unless-stopped
    expose:
      - 8080
    networks:
      - monitor-net
    labels:
      org.label-schema.group: "monitoring"
```

**Comment by xaerowalk** [comment]
>     devices:
>       - /dev/kmsg:/dev/kmsg
Good enough.
Thank you

**Pull request closed without merging**
