### PR TITLE
Fixes #50 alertmanager startup failure

### LINKED ISSUE #50: alertmanager exited with code 1
screen shot 2018-01-16 at 12 39 37 pm

### PR DESCRIPTION
**Pull request by dbachko**

### CODE REVIEW

**Comment by stefanprodan** [comment]
Hi @dbachko 

Can you please update the stack file with a fix image version for alertmanager

**Comment by dbachko** [comment]
@stefanprodan stack file? Sorry, did not get it, where is it located, and what is fix image version for alertmanager?

**Comment by stefanprodan** [comment]
Change the image from `prom/alertmanager` to `prom/alertmanager:v0.13.0` your changes will not work on older version.

**Comment by stefanprodan** [comment]
Thanks

**Pull request merged**
