### PR TITLE
Added loki and promtail

### PR DESCRIPTION
**Pull request by ntimo**
Added Loki and Promtail. https://grafana.com/loki

### CODE REVIEW

**Comment by ntimo** [comment]
This PR makes it possible to see the server logs from Grafana. 
Loki was introduced with Grafana version 6.0.0. 

Example of how the feature look like:
https://grafana.com/video/loki_intro.mp4

**Comment by stefanprodan** [comment]
Hi @ntimo how was this tested? The dockprom should work on Docker for Mac and latest stable Ubuntu/Debian.

**Comment by nightah** [comment]
Reading in to Loki and promtail a little bit more it seems like a great tool but I don't really see it fitting in the landscape of dockprom currently.

Seems in its current state it would be a much better fit for swarmprom @stefanprodan what's your thoughts?

If the vast majority of users want to include it, I'm not averse to including and supporting it. I'm just not entirely sure I would use it, as it stands today.

**Comment by stefanprodan** [comment]
Extending dockprom or swarmprom with logging support needs careful testing and maintenance. When Loki reaches a GA release we could consider it but until then I would not include it.

**Comment by Aschenbecher** [comment]
> Added Loki and Promtail. https://grafana.com/loki

thanks, will implement it in my stack and test!

**Pull request closed without merging**
