### PR TITLE
Added dcgm exporter

### PR DESCRIPTION
**Pull request by maingoh**
related to #148

### CODE REVIEW

**Comment by nightah** [comment]
While this is a great contribution, I'm not entirely sure how useful this would be to include as a default position.

Many dockprom installations may be headless and not even have an nvidia based card with all the respective drivers/pre-reqs.

I'm going to defer to @stefanprodan for his opinion on this.

**Comment by maingoh** [comment]
I agree, this was more an example for those looking to add dcgm. However I can try to make it optional, if you think this is possible ? (i am not so much familiar prometheus).
It can be a python script that would generate the final docker-compose depending on some options ?

**Comment by nightah** [comment]
I think the best way to make it optional would be just to document it in the README, that way if someone wants to add it in, all the information is there.

**Comment by stefanprodan** [comment]
I agree with @nightah I think the NVIDIA exporter could be documented in a separate markdown file and linked from the readme.

**Pull request closed without merging**
