### PR TITLE
fixed the issue that cadvisor keeps restarting with error message: in…

### PR DESCRIPTION
**Pull request by mikephung**
…otify_add_watch /sys/fs/cgroup/cpuacct,cpu: no such file or directory

### CODE REVIEW

**Comment by nightah** [comment]
This looks like it would be a breaking change for a lot of people.
If this is required wouldn't you be better off un-commenting the `/cgroup:/cgroup:ro` mount just below the lines you added?

**Comment by stefanprodan** [comment]
@mikephung  there is no context to this PR, we don't know on what OS cAdvisor keeps restarting. 

I think this change should be made in docs not in the YAMLs by specifying the OS and Docker version.

**Comment by mikephung** [comment]
hi guys,

i obseved this on centos 7 (CentOS Linux release 7.5.1804 (Core)) and uncomment the line won't work on linux nor macos based on the hint right behind this line.

**Comment by mikephung** [comment]
but for sure, we can make it in docs and not in the YAMLs until another people are still facing the same issue.

**Comment by mikephung** [comment]
ok, i got this, was a mistake that i read this line as doesn't work on MacOS & Linux :-( 
`#- /cgroup:/cgroup:ro #doesn't work on MacOS only for Linux`
i modified the uncomment line and activate it and it works 
thanks nightah

**Pull request closed without merging**
